### PR TITLE
1.2.4

### PR DESCRIPTION
**Pull request by andybons**
To pull in fix to `index.js`

### CODE REVIEW

**Comment by samccone** [comment]
@andybons was the missing var causing you any problems?

**Comment by andybons** [comment]
Yes. It was throwing an error on generation. At my phone so I can't paste
it in.

**Comment by samccone** [comment]
Hey @andybons I tracked down the root issue
https://github.com/yeoman/generator-polymer/issues/232#issuecomment-148590099

I will let the person who does the next release handle the bump, thanks!

**Comment by andybons** [comment]
sgtm

**Pull request closed without merging**
