### PR TITLE
Add vulcanize to iron-component-page and demo

### PR DESCRIPTION
**Pull request by abdonrd**
Reference: https://github.com/yeoman/generator-polymer/issues/259

@robdodson I'm not sure if it is the best way. It's the first approach.

### CODE REVIEW

**Comment by robdodson** [comment]
My concern is that we removed polybuild from PSK because it was breaking apps. I'm a little worried the same thing may happen with element demos.

**Comment by abdonrd** [comment]
@robdodson I test it in two personal components and works well.

But... Maybe better change polybuild to only vulcanize?

**Comment by robdodson** [comment]
Yeah I'm more comfortable using vulcanize

**Comment by abdonrd** [comment]
@robdodson updated. But now I have problems...

screen shot 2016-02-10 at 11 37 27

PTAL. :sweat_smile:

**Comment by abdonrd** [comment]
Close in favor to [Polymer/polymer-cli](https://github.com/Polymer/polymer-cli)! 🎉

**Pull request closed without merging**
