### PR TITLE
X-UA-Compatible is deprecated in IE11

### PR DESCRIPTION
**Pull request by arthurvr**
Commit in generator-webapp: https://github.com/yeoman/generator-webapp/commit/c0c2e57bfebad22c30105d0ebb379dbde3b51ae6

### CODE REVIEW

**Comment by hemanth** [comment]
:+1:

**Comment by hemanth** [comment]
Ha, do you think there are people who are using IE version less than 11 for polymer ?

**Comment by robdodson** [comment]
There are some folks out there using IE 10 still. And I've heard scattered
reports of folks trying to get it to work with IE9

**Comment by hemanth** [comment]
@robdodson Should we revert or wait...?

**Comment by robdodson** [comment]
I think it's fine to remove it.

**Comment by hemanth** [comment]
:+1:

**Pull request merged**
